# -*- coding: utf-8 -*-
"""cancer_case_by_state.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6vLo-5-O2zjucMvBkwbVj2pBSWRUHyR
"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

!pip install dash



import pandas as pd
import plotly.express as px
import dash
from dash import dcc, html
from dash.dependencies import Input, Output

# Load melanoma_data.csv
file_path = "/content/drive/My Drive/melanoma_data.csv"  # Update if needed
melanoma_df = pd.read_csv(file_path)

# Ensure correct data types
melanoma_df["Year"] = pd.to_numeric(melanoma_df["Year"], errors='coerce')
melanoma_df["Count"] = pd.to_numeric(melanoma_df["Count"], errors='coerce')

# Initialize Dash app
app = dash.Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Melanoma Cancer Cases by State"),

    # Dropdown to select State
    dcc.Dropdown(
        id="state-dropdown",
        options=[{"label": state, "value": state} for state in melanoma_df["State_Territory"].unique()],
        value=melanoma_df["State_Territory"].unique()[0],  # Default state
        clearable=False
    ),

    # Graph to display the data
    dcc.Graph(id="melanoma-bar-chart")
])

# Callback to update the graph based on selected state
@app.callback(
    Output("melanoma-bar-chart", "figure"),
    Input("state-dropdown", "value")
)
def update_graph(selected_state):
    filtered_df = melanoma_df[melanoma_df["State_Territory"] == selected_state]
    fig = px.bar(
        filtered_df, x="Year", y="Count", color="Sex",
        title=f"Melanoma Cancer Cases in {selected_state}",
        labels={"Count": "Number of Cases", "Year": "Year"}
    )
    return fig

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)