# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBHC94MHYxgv1DKM7OJE2RrT9phrYNge
"""



import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
file_path = "/content/drive/MyDrive/cmip6-x0.25_timeseries_txx_timeseries_annual_1950-2014_median_historical_ensemble_all_mean.xlsx"

# Load the first sheet
df = pd.read_excel(file_path, sheet_name=0, header=None)  # No header in the first row

# Transpose the dataframe to convert columns into rows
df = df.T  # Swap rows & columns

# Rename columns for clarity
df.columns = ["Year", "Temperature"]

# Convert 'Year' to datetime format (Extract only the year)
df["Year"] = df["Year"].astype(str).str[:4]  # Extract YYYY from 'YYYY-MM'
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")  # Convert to numeric

# Convert 'Temperature' to numeric
df["Temperature"] = pd.to_numeric(df["Temperature"], errors="coerce")

# Drop NaN values (if any)
df = df.dropna()

# Sort by Year (Just in case)
df = df.sort_values(by="Year")

# ✅ Print first few rows to check the transformation
print(df.head())

# 📈 Plot the temperature trend
plt.figure(figsize=(10, 5))
plt.plot(df["Year"], df["Temperature"], marker="o", linestyle="-", color="r")

# Formatting
plt.title("Annual Temperature Trend (1950 - 2014)", fontsize=14)
plt.xlabel("Year", fontsize=12)
plt.ylabel("Temperature (°C)", fontsize=12)
plt.grid(True)

# Show the plot
plt.show()